// Added a custom type declaration for 'lucide-react' to resolve missing type issues.
declare module 'lucide-react' {
  import * as React from 'react';
  export type IconProps = React.SVGProps<SVGSVGElement>;
  export const Play: React.FC<IconProps>;
  export const Info: React.FC<IconProps>;
  export const SearchIcon: React.FC<IconProps>;
  export const SlidersHorizontal: React.FC<IconProps>;
  export const ChevronDownIcon: React.FC<IconProps>;
  export const StarIcon: React.FC<IconProps>;
  export const CalendarIcon: React.FC<IconProps>;
  export const ClockIcon: React.FC<IconProps>;
  export const Clapperboard: React.FC<IconProps>;
  export const BookmarkPlus: React.FC<IconProps>;
  export const Share2: React.FC<IconProps>;
  export const ChevronRight: React.FC<IconProps>;
  export const ChevronLeft: React.FC<IconProps>;
  export const ChevronUp: React.FC<IconProps>;
  export const ChevronDown: React.FC<IconProps>;
  export const ArrowRight: React.FC<IconProps>;
  export const ArrowLeft: React.FC<IconProps>;
  export const X: React.FC<IconProps>;
  export const Plus: React.FC<IconProps>;
  export const Minus: React.FC<IconProps>;
  export const Trash: React.FC<IconProps>;
  export const Edit: React.FC<IconProps>;
  export const Check: React.FC<IconProps>;
  export const ThumbsDown: React.FC<IconProps>;
  export const ThumbsUp: React.FC<IconProps>;
  export const User: React.FC<IconProps>;
  export const Settings: React.FC<IconProps>;
  export const Heart: React.FC<IconProps>;
  export const BookOpen: React.FC<IconProps>;
  export const MessageSquare: React.FC<IconProps>;
  export const Clock: React.FC<IconProps>;
  export const Award: React.FC<IconProps>;
  export const UserRound : React.FC<IconProps>;
  export const MailIcon: React.FC<IconProps>;
  export const LockIcon: React.FC<IconProps>;
  export const EyeIcon: React.FC<IconProps>;
  export const EyeOffIcon: React.FC<IconProps>;
  export const TrendingUp: React.FC<IconProps>;
  export const Users: React.FC<IconProps>;
  export const Mail: React.FC<IconProps>;
  export const Instagram: React.FC<IconProps>;
  export const Twitter: React.FC<IconProps>;
  export const Youtube: React.FC<IconProps>;
  export const Lock: React.FC<IconProps>;
  export const Shield: React.FC<IconProps>;
  export const Bookopen: React.FC<IconProps>;
  export const Monitor: React.FC<IconProps>;
  export const Home: React.FC<IconProps>;
  export const Film: React.FC<IconProps>;
  export const Newspaper: React.FC<IconProps>;
  export const Calendar: React.FC<IconProps>;
  export const Star: React.FC<IconProps>;
  export const Map: React.FC<IconProps>;
  export const Bookmark: React.FC<IconProps>;
  export const Zap: React.FC<IconProps>;
  export const BarChart3: React.FC<IconProps>;
  export const ChevronRight: React.FC<IconProps>;
  export const ChevronLeft: React.FC<IconProps>;
  export const ChevronUp: React.FC<IconProps>;
  export const ChevronDown: React.FC<IconProps>;
  export const ChevronRight: React.FC<IconProps>;
  export const ChevronLeft: React.FC<IconProps>;
  export const ChevronUp: React.FC<IconProps>;
  export const ChevronDown: React.FC<IconProps>;
  export const Eye: React.FC<IconProps>;

  export const ChevronRight: React.FC<IconProps>;
  export declare const Menu: LucideIcon;
  export declare const Search: LucideIcon;
  export declare const Bell: LucideIcon;
  export declare const LogOut: LucideIcon;

}